function init(self)
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	--defos.disable_maximize_button()
	defos.disable_window_resize()
	
	self.speed = 200
end

function update(self, dt)
	local pos = go.get_position()
	pos.y = pos.y - self.speed * dt

	if pos.y <= -512 then
		pos.y = 0
	end
	
	go.set_position(pos)
end

function on_message(self, message_id, message)
	if message_id == hash('stop') then
		self.speed = 0
	end
end